config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/todos', to: 'todos#index'
  get 'todos/new'
  post '/todos', to: 'todos#create'
  get 'todos/list', to: 'todos#list'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'cambiar'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get '/todos/:id/complete', to: 'todos#complete', as: 'fill'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_path
  end

  def show
    @todos = Todo.find(params[:id])
  end

  def edit
    @todos = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todos = Todo.find(params[:id])
    @todos.destroy
    redirect_to todos_path
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
  end

  private

  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar'%>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f| %>
<%= f.label :description, "Descripción" %>
<%= f.text_field :description %>
<%= f.label :completed, "Check" %>
<%= f.check_box :completed %>
<%= f.submit "Enviar" %>
<% end %>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href='<%= todos_path %>'>Inicio</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "List", todos_list_path %> </li>
        <li><%= link_to "New", todos_new_path %></li>
      </ul>
      </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/todos/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <%= form_with model: @todos, local: true do |f| %>
    <%= f.label :description, "Descripción" %>
    <%= f.text_field :description %>
    <%= f.label :completed, "Check" %>
    <%= f.check_box :completed %>
    <%= f.submit "Enviar" %>
    <% end %>
  </body>
</html>

app/views/todos/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <h1>Index</h1>
      <% @todos.each do |i| %>
       <div class = "well"> <h2><%= link_to i.description, todo_path(i.id) %></h2>
       <p><%= link_to "Check", fill_path(i.id)%></p>
       <p><%= link_to "Show", todo_path(i.id)%></p>
       <p><%= link_to "Edit", cambiar_path(i.id)%></p>
       <p><%= link_to "Borrar", i, method: :delete %></p>
       </div>
       <% end %>
     <p class = "btn btn-primary"><%= link_to "Nuevo ToDo", todos_new_path %></p>

  </body>
</html>

app/views/todos/list.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="row"></div>
    <div class="container">
    <% @todos.each do |i| %>
    <% if i.completed == true %>
    <div class="col-md-6"><%= i.description %></div>
    <% end %>
    <% end %>
    <% @todos.each do |i| %>
    <% if i.completed == false %>
    <div class="col-md-6"><%= i.description %></div>
    <% end %>
    <% end %>


    </div>

  </body>
</html>

app/views/todos/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <%= render 'todos/form' %>

  </body>
</html>

app/views/todos/show.html.erb
<h1>Descrición</h1>
<h2><%= @todos.description %></h2>
<h1>Estado</h1>
<h2><%= @todos.completed %></h2>